// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYyNCeOcnrJ7NUMb4idTO1rC0ym-PNpTQ',
    appId: '1:57032811526:web:0ddcbf13397ec7ad258f87',
    messagingSenderId: '57032811526',
    projectId: 'cavalcade-2c924',
    authDomain: 'cavalcade-2c924.firebaseapp.com',
    storageBucket: 'cavalcade-2c924.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf8LO5AKF9SvAHNbCX8VMf5KMpXncnibk',
    appId: '1:57032811526:android:232a265cf70d3069258f87',
    messagingSenderId: '57032811526',
    projectId: 'cavalcade-2c924',
    storageBucket: 'cavalcade-2c924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTrGyxKvAVj7JQbc5TkXjhvE0364K3nCQ',
    appId: '1:57032811526:ios:cad4461fc99d8953258f87',
    messagingSenderId: '57032811526',
    projectId: 'cavalcade-2c924',
    storageBucket: 'cavalcade-2c924.appspot.com',
    iosBundleId: 'com.example.cavalcade',
  );
}
